server:
  port: 8080
  servlet:
    context-path: /lemon 
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/api-runner
    url: jdbc:mysql://119.23.238.138:3316/api-runner?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
    username: root
    password: java
#     password: root

